version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  db:
    container_name: 'Postgres'
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'

  web:
    container_name: 'sanic'
    build: '.'
    restart: on-failure
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    command: >
      sh -c "python link_shortener/core/wait_for_db_and_migrate.py &&
             python link_shortener/server.py"
    depends_on:
      - 'db'
    links:
      - 'db'
